---
- name: Create runtime host from survey input
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Add target server dynamically
      add_host:
        name: runtime_target
        ansible_host: "{{ target_ip }}"
        ansible_user: "{{ ssh_user }}"
        ansible_password: "{{ ssh_password }}"
        ansible_port: "{{ ssh_port }}"
        ansible_connection: ssh


- name: Bootstrap Linux Server
  hosts: runtime_target
  become: true
  gather_facts: true

  roles:
    - common


  tasks:

    - name: Register host into AWX inventory
      run_once: true
      awx.awx.host:
        controller_host: "{{ lookup('env','CONTROLLER_HOST') }}"
        controller_oauthtoken: "{{ lookup('env','CONTROLLER_OAUTH_TOKEN') }}"

        name: "{{ vm_name }}"
        inventory: "{{ environment | default('Non-Production') }}"

        variables:
          ansible_host: "{{ target_ip }}"
          ansible_user: "{{ ssh_user }}"
          ansible_port: "{{ ssh_port }}"

        state: present