---
# ansible/inventories/prod/hosts.yml
all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    environment: prod

  children:
    app_servers:
      hosts:
        prod-server-01:
          ansible_host: 10.0.1.10
        prod-server-02:
          ansible_host: 10.0.1.11
    db_servers:
      hosts:
        prod-db-01:
          ansible_host: 10.0.1.20
