---
# Ansible Inventory — Production
all:
  children:
    awx_servers:
      hosts:
        prod-awx01:
          ansible_host: REPLACE_WITH_PROD_IP
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3
          # Environment
          env: prod
          public_ip: REPLACE_WITH_PROD_PUBLIC_IP
          rancher_hostname: "rancher.yourdomain.com"
          awx_hostname: "awx.yourdomain.com"
