---
timezone: Asia/Phnom_Penh

common_packages:
  - vim
  - git
  - curl
  - wget
  - unzip
  - bash-completion
  - chrony

admin_users:
  - devops

ssh_public_keys:
  devops: "ssh-rsa AAAAB3NzaC1xxxxx"