- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Replace localhost with node IP
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: 'server: https://127.0.0.1:6443'
    replace: "server: https://{{ ansible_host }}:6443"
