---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    k3s_role: server

# k3s_masters:
#   hosts:
#     awx-master-01:
#       ansible_host: 192.168.1.10
#       ip: 192.168.1.10
#       k3s_role: server
#     # awx-master-02:
#     #   ansible_host: 192.168.1.11
#     #   ip: 192.168.1.11
#     #   k3s_role: server


# ansible/inventory/hosts.yml
# This is a sample Ansible inventory file for deploying k3s on a single master node.
k3s_masters:
  hosts:
    awx-master-01:
      ansible_host: 172.16.0.0
      ansible_connection: local   # ← no SSH needed
      ip: <server-private-ip>     # ← used by k3s for node binding
      k3s_role: server

# k3s_workers:
#   hosts: {}
#   # awx-worker-01:
#   #   ansible_host: 192.168.1.20
#   #   ip: 192.168.1.20
#   #   k3s_role: agent
