- name: Install prerequisites (Oracle Linux)
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - git
    - python3-pip
    - net-tools
    - firewalld

- name: Ensure firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: true

# - name: Open required firewall ports
#   firewalld:
#     port: "{{ item }}"
#     permanent: true
#     state: enabled
#     immediate: true
#   loop:
#     - 6443/tcp
#     - 80/tcp
#     - 443/tcp
#     - 5432/tcp

- name: Set SELinux permissive
  selinux:
    policy: targeted
    state: permissive

- name: Set timezone
  timezone:
    name: "{{ timezone | default('Asia/Phnom_Penh') }}"
