---
# Ansible Inventory — Dev/UAT
all:
  children:
    awx_servers:
      hosts:
        uat-awx01:
          ansible_host: 10.0.0.4
          ansible_user: azureuser
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_become: true
          ansible_python_interpreter: /usr/bin/python3
          # Environment
          env: uat
          public_ip: 20.84.49.131
          rancher_hostname: "20.84.49.131.nip.io"
          awx_hostname: "awx.20.84.49.131.nip.io"
