---
- name: Set timezone
  timezone:
    name: Asia/Phnom_Penh

- name: Install common packages
  package:
    name:
      - vim
      - curl
      - wget
      - git
    state: present

- name: Ensure sudo user
  user:
    name: root
    groups: wheel
    append: yes