# k8s/overlays/dev/patch-resources.yaml
# Reduce resource requirements for the dev environment
- op: replace
  path: /spec/replicas
  value: 1

- op: replace
  path: /spec/web_resource_requirements
  value:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

- op: replace
  path: /spec/task_resource_requirements
  value:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

- op: replace
  path: /spec/projects_storage_size
  value: "4Gi"
