# k8s/overlays/staging/patch-resources.yaml
- op: replace
  path: /spec/replicas
  value: 1

- op: replace
  path: /spec/web_resource_requirements
  value:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

- op: replace
  path: /spec/task_resource_requirements
  value:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

- op: replace
  path: /spec/projects_storage_size
  value: "8Gi"

# Enable HTTPS security settings for staging/prod
- op: add
  path: /spec/extra_settings/-
  value:
    setting: SESSION_COOKIE_SECURE
    value: "true"

- op: add
  path: /spec/extra_settings/-
  value:
    setting: CSRF_COOKIE_SECURE
    value: "true"
